"""add_risk_score_model

Revision ID: a3c6cbaaf8b6
Revises: 25f03231638b
Create Date: 2025-07-11 12:03:19.294490

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a3c6cbaaf8b6"
down_revision: Union[str, None] = "25f03231638b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
          CREATE TYPE aireviewstatusenum AS ENUM (
            'PENDING',
            'FLAGGED',
            'CLEARED',
            'CONFIRMED_FRAUD'
          );
        """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column(
            "ai_review_status",
            sa.Enum(
                "PENDING",
                "FLAGGED",
                "CLEARED",
                "CONFIRMED_FRAUD",
                name="aireviewstatusenum",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "ai_review_status")

    op.execute("DROP TYPE aireviewstatusenum;")
    # ### end Alembic commands ###
